apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{ .Values.labels | toYaml | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{ .Values.labels | toYaml | nindent 6 }}
  template:
    metadata:
      labels:
        {{ .Values.labels | toYaml | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.deployment.image }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        env:
        - name: {{ .Values.deployment.envVar.username }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: {{ .Values.secret.usernameKey }}
        - name: {{ .Values.deployment.envVar.password }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: {{ .Values.secret.passwordKey }}
        resources:
          {{ .Values.deployment.resources | toYaml | nindent 10 }}