apiVersion: deviceregistry.microsoft.com/v1
kind: AssetEndpointProfile
metadata:
  name: my-rest-thermostat-profile
  namespace: azure-iot-operations
spec:
  authentication:
    method: UsernamePassword
    usernamePasswordCredentials:
      usernameSecretName: rest-server-auth-creds/username
      passwordSecretName: rest-server-auth-creds/password
  discoveredAssetEndpointProfileRef: my-rest-thermostat-discovered-asset-endpoint-profile
  endpointProfileType: rest-thermostat
  targetAddress: http://rest-server-service.azure-iot-operations.svc.cluster.local:80
  uuid: 1234-5678-9012-3456