name: Create git tag
on: 
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  Build-Code:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@220e0dd7bb9b1a6d5645cb78f7d02a3c39c45803 # v1.0.0
      with:
        versionSpec: '5.x'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@220e0dd7bb9b1a6d5645cb78f7d02a3c39c45803 # v1.0.0
      with:
        useConfigFile: true
    - name: Create git tag
      run: |
        git tag ${{ env.GitVersion_MajorMinorPatch }}
    #   if: github.ref == 'refs/heads/main'
    - name: Push git tag
      run: git push origin ${{ env.GitVersion_MajorMinorPatch }}
      # if: github.ref == 'refs/heads/main'